### ISSUE TITLE
Example not working on Stackblitz

### ISSUE THREAD

**Issue by djmtype** [Diizzayy/nuxt-graphql-client#44]
Opening the example found here, https://nuxt-graphql-client.web.app/#nuxt-graphql-client, doesn't work – fails to load schema.

**Comment by Diizzayy** [comment]
@djmtype Thank you for pointing this out.

It should now be working properly. Feel free to test it out https://stackblitz.com/github/diizzayy/nuxt-graphql-client-demo

**Comment by iBobik** [comment]
@Diizzayy On the website there is still not working version.

**Comment by iBobik** [comment]
SpaceX API stopped working, you can use this public API from one of my repros: https://stackblitz.com/edit/github-twqhau?file=app.vue
